

services:

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/aladia
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_HOST=authentication
      - AUTH_PORT=3001
    depends_on:
      - mongo
      - redis
      - authentication

  authentication:
    build:
      context: .
      dockerfile: apps/authentication/Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/aladia
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

volumes:
  mongo_data: